version: '3'

services:
  mongodb:
    image: mongo:4.4.24
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  node-app:
    build:
      context: .
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    links:
      - mongodb

volumes:
  mongo-data:
